version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Iniciando sesión en Docker Hub...
  build:
    commands:
      - echo Construyendo la imagen de Docker...
      - docker build -t mi-app ./app
  post_build:
    commands:
      - echo Construcción terminada.
artifacts:
  files:
    - '**/*'